#version: '3.0.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/ruby_appsec-db-1:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rake ruby_appsec-db-1:create && rake ruby_appsec-db-1:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 8880 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "8880:8880"
    depends_on:
      - db
