#   gem install postgresql
#
#   gem "postgresql"
#
#   gem install postgresql
#
#   gem "postgresql"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: ruby_appsec-db-1
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: sql_injection_dev

test:
  <<: *default
  database: sql_injection_test

production:
  <<: *default
  database: sql_injection_prod
