name: Ruby on Rails

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run : |
          docker compose build
          docker compose up -d

      - name: Build Tailwind CSS
        run: |
          docker exec -it ruby_appsec-web-1 bash
          rails tailwindcss:watch

     # - name: Load CSS
     #   run : |
     #     docker exec -it ruby_appsec-web-1 bash
     #     rails tailwindcss:watch
